- hosts: web1
  tasks:
    - name: Tranfer template to web server
      template:
        src: table.j2
        dest: /var/www/html/index.php
    - name: Task Name
      debug:
        msg: "The people age is {{ PEOPLE_AGE }}"